/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as CreateRouteImport } from './routes/create'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripIdRouteImport } from './routes/trip.$id'
import { Route as SharedIdRouteImport } from './routes/shared.$id'
import { Route as TripIdViewRouteImport } from './routes/trip.$id.view'
import { Route as TripIdPackingRouteImport } from './routes/trip.$id.packing'
import { Route as TripIdNotesRouteImport } from './routes/trip.$id.notes'
import { Route as TripIdBuildRouteImport } from './routes/trip.$id.build'
import { Route as TripIdBudgetRouteImport } from './routes/trip.$id.budget'

const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripIdRoute = TripIdRouteImport.update({
  id: '/trip/$id',
  path: '/trip/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedIdRoute = SharedIdRouteImport.update({
  id: '/shared/$id',
  path: '/shared/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TripIdViewRoute = TripIdViewRouteImport.update({
  id: '/view',
  path: '/view',
  getParentRoute: () => TripIdRoute,
} as any)
const TripIdPackingRoute = TripIdPackingRouteImport.update({
  id: '/packing',
  path: '/packing',
  getParentRoute: () => TripIdRoute,
} as any)
const TripIdNotesRoute = TripIdNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => TripIdRoute,
} as any)
const TripIdBuildRoute = TripIdBuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => TripIdRoute,
} as any)
const TripIdBudgetRoute = TripIdBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => TripIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trips': typeof TripsRoute
  '/shared/$id': typeof SharedIdRoute
  '/trip/$id': typeof TripIdRouteWithChildren
  '/trip/$id/budget': typeof TripIdBudgetRoute
  '/trip/$id/build': typeof TripIdBuildRoute
  '/trip/$id/notes': typeof TripIdNotesRoute
  '/trip/$id/packing': typeof TripIdPackingRoute
  '/trip/$id/view': typeof TripIdViewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trips': typeof TripsRoute
  '/shared/$id': typeof SharedIdRoute
  '/trip/$id': typeof TripIdRouteWithChildren
  '/trip/$id/budget': typeof TripIdBudgetRoute
  '/trip/$id/build': typeof TripIdBuildRoute
  '/trip/$id/notes': typeof TripIdNotesRoute
  '/trip/$id/packing': typeof TripIdPackingRoute
  '/trip/$id/view': typeof TripIdViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trips': typeof TripsRoute
  '/shared/$id': typeof SharedIdRoute
  '/trip/$id': typeof TripIdRouteWithChildren
  '/trip/$id/budget': typeof TripIdBudgetRoute
  '/trip/$id/build': typeof TripIdBuildRoute
  '/trip/$id/notes': typeof TripIdNotesRoute
  '/trip/$id/packing': typeof TripIdPackingRoute
  '/trip/$id/view': typeof TripIdViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/create'
    | '/profile'
    | '/reset-password'
    | '/trips'
    | '/shared/$id'
    | '/trip/$id'
    | '/trip/$id/budget'
    | '/trip/$id/build'
    | '/trip/$id/notes'
    | '/trip/$id/packing'
    | '/trip/$id/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/create'
    | '/profile'
    | '/reset-password'
    | '/trips'
    | '/shared/$id'
    | '/trip/$id'
    | '/trip/$id/budget'
    | '/trip/$id/build'
    | '/trip/$id/notes'
    | '/trip/$id/packing'
    | '/trip/$id/view'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/create'
    | '/profile'
    | '/reset-password'
    | '/trips'
    | '/shared/$id'
    | '/trip/$id'
    | '/trip/$id/budget'
    | '/trip/$id/build'
    | '/trip/$id/notes'
    | '/trip/$id/packing'
    | '/trip/$id/view'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CreateRoute: typeof CreateRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TripsRoute: typeof TripsRoute
  SharedIdRoute: typeof SharedIdRoute
  TripIdRoute: typeof TripIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$id': {
      id: '/trip/$id'
      path: '/trip/$id'
      fullPath: '/trip/$id'
      preLoaderRoute: typeof TripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$id': {
      id: '/shared/$id'
      path: '/shared/$id'
      fullPath: '/shared/$id'
      preLoaderRoute: typeof SharedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$id/view': {
      id: '/trip/$id/view'
      path: '/view'
      fullPath: '/trip/$id/view'
      preLoaderRoute: typeof TripIdViewRouteImport
      parentRoute: typeof TripIdRoute
    }
    '/trip/$id/packing': {
      id: '/trip/$id/packing'
      path: '/packing'
      fullPath: '/trip/$id/packing'
      preLoaderRoute: typeof TripIdPackingRouteImport
      parentRoute: typeof TripIdRoute
    }
    '/trip/$id/notes': {
      id: '/trip/$id/notes'
      path: '/notes'
      fullPath: '/trip/$id/notes'
      preLoaderRoute: typeof TripIdNotesRouteImport
      parentRoute: typeof TripIdRoute
    }
    '/trip/$id/build': {
      id: '/trip/$id/build'
      path: '/build'
      fullPath: '/trip/$id/build'
      preLoaderRoute: typeof TripIdBuildRouteImport
      parentRoute: typeof TripIdRoute
    }
    '/trip/$id/budget': {
      id: '/trip/$id/budget'
      path: '/budget'
      fullPath: '/trip/$id/budget'
      preLoaderRoute: typeof TripIdBudgetRouteImport
      parentRoute: typeof TripIdRoute
    }
  }
}

interface TripIdRouteChildren {
  TripIdBudgetRoute: typeof TripIdBudgetRoute
  TripIdBuildRoute: typeof TripIdBuildRoute
  TripIdNotesRoute: typeof TripIdNotesRoute
  TripIdPackingRoute: typeof TripIdPackingRoute
  TripIdViewRoute: typeof TripIdViewRoute
}

const TripIdRouteChildren: TripIdRouteChildren = {
  TripIdBudgetRoute: TripIdBudgetRoute,
  TripIdBuildRoute: TripIdBuildRoute,
  TripIdNotesRoute: TripIdNotesRoute,
  TripIdPackingRoute: TripIdPackingRoute,
  TripIdViewRoute: TripIdViewRoute,
}

const TripIdRouteWithChildren =
  TripIdRoute._addFileChildren(TripIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CreateRoute: CreateRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TripsRoute: TripsRoute,
  SharedIdRoute: SharedIdRoute,
  TripIdRoute: TripIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
